//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSString;

@interface FBLigerConfig : NSObject
{
    _Bool _ligerEnabled;
    _Bool _allRequestsEnabled;
    _Bool _dnsCacheEnabled;
    _Bool _requestProcessLogEnabled;
    _Bool _cAresEnabled;
    _Bool _persistentSSLCacheEnabled;
    _Bool _crossDomainSSLCacheEnabled;
    _Bool _httpSessionManagerOriginLimitEnabled;
    _Bool _limitVideoDomain;
    _Bool _heV4PrefEnabled;
    _Bool _tcpPingEnabled;
    _Bool _tcpPingCancelOnReply;
    _Bool _tcpPingAdaptiveTimeout;
    _Bool _tcpReuseEnabled;
    _Bool _sslCertKeyLengthVerificationEnforced;
    _Bool _sslTimestampVerificationEnabled;
    _Bool _zeroProtocolEnabled;
    _Bool _zeroProtocolEnforceExpiration;
    _Bool _zeroProtocolPersistentCache;
    _Bool _zeroRetryEnabled;
    _Bool _radioMonitorEnabled;
    _Bool _altSvcEnabled;
    _Bool _flowControlEnabled;
    _Bool _enableCachingPushManager;
    int _dnsRequestsOutstanding;
    int _persistentSSLCacheCapacity;
    int _persistentSSLCacheSyncInterval;
    int _zeroTlsFallback;
    int _http2PriLevels;
    NSString *_dnsFallbackAnswers;
    NSString *_persistentSSLCacheFilename;
    long long _httpSessionManagerMaxIdleHTTPSessions;
    long long _httpSessionManagerMaxIdleSPDYSessions;
    long long _httpSessionManagerBackupTimeout;
    long long _httpSessionManagerOriginMaxRetries;
    long long _tcpPingTimeout;
    long long _tcpPingRetries;
    unsigned long long _tcpPingRttThreshold;
    unsigned long long _tcpInfoCacheTime;
//    id <FBLigerProvidesNetworkStatusMonitor> _ligerNetworkStatusMonitor;
    NSArray *_requestObservers;
//    id <FBLigerProvidesConnectionLogger> _ligerConnectionLogger;
//    CDUnknownBlockType _proxyUserAgentFormattingBlock;
    NSString *_zeroProtocolAeads;
    NSString *_zeroProtocolHostnamePolicy;
    NSString *_http2PriReqCallPaths;
    NSString *_http2PriWeights;
    long long _flowControlWindowSize;
    NSArray *_pushNotificationCallbacks;
}

@property(readonly, copy, nonatomic) NSArray *pushNotificationCallbacks; // @synthesize pushNotificationCallbacks=_pushNotificationCallbacks;
@property(readonly, nonatomic) _Bool enableCachingPushManager; // @synthesize enableCachingPushManager=_enableCachingPushManager;
@property(readonly, nonatomic) long long flowControlWindowSize; // @synthesize flowControlWindowSize=_flowControlWindowSize;
@property(readonly, nonatomic) _Bool flowControlEnabled; // @synthesize flowControlEnabled=_flowControlEnabled;
@property(readonly, nonatomic) _Bool altSvcEnabled; // @synthesize altSvcEnabled=_altSvcEnabled;
@property(readonly, nonatomic) _Bool radioMonitorEnabled; // @synthesize radioMonitorEnabled=_radioMonitorEnabled;
@property(readonly, copy, nonatomic) NSString *http2PriWeights; // @synthesize http2PriWeights=_http2PriWeights;
@property(readonly, copy, nonatomic) NSString *http2PriReqCallPaths; // @synthesize http2PriReqCallPaths=_http2PriReqCallPaths;
@property(readonly, nonatomic) int http2PriLevels; // @synthesize http2PriLevels=_http2PriLevels;
@property(readonly, nonatomic) int zeroTlsFallback; // @synthesize zeroTlsFallback=_zeroTlsFallback;
@property(readonly, nonatomic) _Bool zeroRetryEnabled; // @synthesize zeroRetryEnabled=_zeroRetryEnabled;
@property(readonly, copy, nonatomic) NSString *zeroProtocolHostnamePolicy; // @synthesize zeroProtocolHostnamePolicy=_zeroProtocolHostnamePolicy;
@property(readonly, copy, nonatomic) NSString *zeroProtocolAeads; // @synthesize zeroProtocolAeads=_zeroProtocolAeads;
@property(readonly, nonatomic) _Bool zeroProtocolPersistentCache; // @synthesize zeroProtocolPersistentCache=_zeroProtocolPersistentCache;
@property(readonly, nonatomic) _Bool zeroProtocolEnforceExpiration; // @synthesize zeroProtocolEnforceExpiration=_zeroProtocolEnforceExpiration;
@property(readonly, nonatomic) _Bool zeroProtocolEnabled; // @synthesize zeroProtocolEnabled=_zeroProtocolEnabled;
@property(readonly, nonatomic) _Bool sslTimestampVerificationEnabled; // @synthesize sslTimestampVerificationEnabled=_sslTimestampVerificationEnabled;
@property(readonly, nonatomic) _Bool sslCertKeyLengthVerificationEnforced; // @synthesize sslCertKeyLengthVerificationEnforced=_sslCertKeyLengthVerificationEnforced;
//@property(readonly, copy, nonatomic) CDUnknownBlockType proxyUserAgentFormattingBlock; // @synthesize proxyUserAgentFormattingBlock=_proxyUserAgentFormattingBlock;
//@property(nonatomic) id <FBLigerProvidesConnectionLogger> ligerConnectionLogger; // @synthesize ligerConnectionLogger=_ligerConnectionLogger;
@property(copy, nonatomic) NSArray *requestObservers; // @synthesize requestObservers=_requestObservers;
//@property(nonatomic) id <FBLigerProvidesNetworkStatusMonitor> ligerNetworkStatusMonitor; // @synthesize ligerNetworkStatusMonitor=_ligerNetworkStatusMonitor;
@property(readonly, nonatomic) _Bool tcpReuseEnabled; // @synthesize tcpReuseEnabled=_tcpReuseEnabled;
@property(readonly, nonatomic) unsigned long long tcpInfoCacheTime; // @synthesize tcpInfoCacheTime=_tcpInfoCacheTime;
@property(readonly, nonatomic) _Bool tcpPingAdaptiveTimeout; // @synthesize tcpPingAdaptiveTimeout=_tcpPingAdaptiveTimeout;
@property(readonly, nonatomic) unsigned long long tcpPingRttThreshold; // @synthesize tcpPingRttThreshold=_tcpPingRttThreshold;
@property(readonly, nonatomic) _Bool tcpPingCancelOnReply; // @synthesize tcpPingCancelOnReply=_tcpPingCancelOnReply;
@property(readonly, nonatomic) long long tcpPingRetries; // @synthesize tcpPingRetries=_tcpPingRetries;
@property(readonly, nonatomic) long long tcpPingTimeout; // @synthesize tcpPingTimeout=_tcpPingTimeout;
@property(readonly, nonatomic) _Bool tcpPingEnabled; // @synthesize tcpPingEnabled=_tcpPingEnabled;
@property(readonly, nonatomic) _Bool heV4PrefEnabled; // @synthesize heV4PrefEnabled=_heV4PrefEnabled;
@property(readonly, nonatomic) _Bool limitVideoDomain; // @synthesize limitVideoDomain=_limitVideoDomain;
@property(readonly, nonatomic) long long httpSessionManagerOriginMaxRetries; // @synthesize httpSessionManagerOriginMaxRetries=_httpSessionManagerOriginMaxRetries;
@property(readonly, nonatomic) _Bool httpSessionManagerOriginLimitEnabled; // @synthesize httpSessionManagerOriginLimitEnabled=_httpSessionManagerOriginLimitEnabled;
@property(readonly, nonatomic) long long httpSessionManagerBackupTimeout; // @synthesize httpSessionManagerBackupTimeout=_httpSessionManagerBackupTimeout;
@property(readonly, nonatomic) long long httpSessionManagerMaxIdleSPDYSessions; // @synthesize httpSessionManagerMaxIdleSPDYSessions=_httpSessionManagerMaxIdleSPDYSessions;
@property(readonly, nonatomic) long long httpSessionManagerMaxIdleHTTPSessions; // @synthesize httpSessionManagerMaxIdleHTTPSessions=_httpSessionManagerMaxIdleHTTPSessions;
@property(readonly, nonatomic) _Bool crossDomainSSLCacheEnabled; // @synthesize crossDomainSSLCacheEnabled=_crossDomainSSLCacheEnabled;
@property(readonly, nonatomic) int persistentSSLCacheSyncInterval; // @synthesize persistentSSLCacheSyncInterval=_persistentSSLCacheSyncInterval;
@property(readonly, nonatomic) int persistentSSLCacheCapacity; // @synthesize persistentSSLCacheCapacity=_persistentSSLCacheCapacity;
@property(copy, nonatomic) NSString *persistentSSLCacheFilename; // @synthesize persistentSSLCacheFilename=_persistentSSLCacheFilename;
@property(readonly, nonatomic) _Bool persistentSSLCacheEnabled; // @synthesize persistentSSLCacheEnabled=_persistentSSLCacheEnabled;
@property(readonly, copy, nonatomic) NSString *dnsFallbackAnswers; // @synthesize dnsFallbackAnswers=_dnsFallbackAnswers;
@property(readonly, nonatomic) int dnsRequestsOutstanding; // @synthesize dnsRequestsOutstanding=_dnsRequestsOutstanding;
@property(readonly, nonatomic) _Bool cAresEnabled; // @synthesize cAresEnabled=_cAresEnabled;
@property(readonly, nonatomic) _Bool requestProcessLogEnabled; // @synthesize requestProcessLogEnabled=_requestProcessLogEnabled;
@property(readonly, nonatomic) _Bool dnsCacheEnabled; // @synthesize dnsCacheEnabled=_dnsCacheEnabled;
@property(readonly, nonatomic) _Bool allRequestsEnabled; // @synthesize allRequestsEnabled=_allRequestsEnabled;
@property(readonly, nonatomic) _Bool ligerEnabled; // @synthesize ligerEnabled=_ligerEnabled;
- (_Bool)isEqualToFBLigerConfig:(id)arg1;
- (id)initDefaultConfigWithProxyUserAgentFormattingBlock:(id)arg1;
- (id)initConfigWithLigerEnabled:(_Bool)arg1 allRequestsEnabled:(_Bool)arg2 dnsCacheEnabled:(_Bool)arg3 requestProcessLogEnabled:(_Bool)arg4 cAresEnabled:(_Bool)arg5 dnsRequestsOutstanding:(int)arg6 dnsFallbackAnswers:(id)arg7 persistentSSLCacheEnabled:(_Bool)arg8 persistentSSLCacheFilename:(id)arg9 persistentSSLCacheCapacity:(int)arg10 persistentSSLCacheSyncInterval:(int)arg11 crossDomainSSLCacheEnabled:(_Bool)arg12 httpSessionManagerMaxIdleHTTPSessions:(long long)arg13 httpSessionManagerMaxIdleSPDYSessions:(long long)arg14 httpSessionManagerBackupTimeout:(long long)arg15 httpSessionManagerOriginLimitEnabled:(_Bool)arg16 httpSessionManagerOriginMaxRetries:(long long)arg17 limitVideoDomain:(_Bool)arg18 heV4PrefEnabled:(_Bool)arg19 tcpPingEnabled:(_Bool)arg20 tcpPingRetries:(long long)arg21 tcpPingTimeout:(long long)arg22 tcpPingCancelOnReply:(_Bool)arg23 tcpPingRttThreshold:(unsigned long long)arg24 tcpPingAdaptiveTimeout:(_Bool)arg25 tcpInfoCacheTime:(unsigned long long)arg26 tcpReuseEnabled:(_Bool)arg27 ligerNetworkStatusMonitor:(id)arg28 requestObservers:(id)arg29 ligerConnectionLogger:(id)arg30 sslCertKeyLengthVerificationEnforced:(_Bool)arg31 sslTimestampVerificationEnabled:(_Bool)arg32 zeroProtocolEnabled:(_Bool)arg33 zeroProtocolEnforceExpiration:(_Bool)arg34 zeroProtocolPersistentCache:(_Bool)arg35 zeroProtocolAeads:(id)arg36 zeroProtocolHostnamePolicy:(id)arg37 zeroRetryEnabled:(_Bool)arg38 zeroTlsFallback:(int)arg39 http2PriLevels:(int)arg40 http2PriReqCallPaths:(id)arg41 http2PriWeights:(id)arg42 radioMonitorEnabled:(_Bool)arg43 altSvcEnabled:(_Bool)arg44 flowControlEnabled:(_Bool)arg45 flowControlWindowSize:(long long)arg46 enableCachingPushManager:(_Bool)arg47 pushNotificationCallbacks:(id)arg48 proxyUserAgentFormattingBlock:(id)arg49;

@end

